# Generated by Django 4.2.13 on 2026-03-06 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_alter_answeroption_id_alter_question_id_and_more"),
        ("quiz_sessions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="playeranswer",
            name="unique_player_question_answer",
        ),
        migrations.RenameIndex(
            model_name="playeranswer",
            new_name="quiz_sessio_player__081bf9_idx",
            old_name="sessions_pa_player_q_idx",
        ),
        migrations.RenameIndex(
            model_name="playersession",
            new_name="quiz_sessio_game_se_e1aea6_idx",
            old_name="sessions_pl_game_se_idx",
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="playeranswer",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="playeranswer",
            name="response_time",
            field=models.FloatField(help_text="Seconds to answer"),
        ),
        migrations.AlterField(
            model_name="playersession",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playeranswer",
            unique_together={("player_session", "question")},
        ),
        migrations.AlterModelTable(
            name="gamesession",
            table="quiz_sessions_gamesession",
        ),
        migrations.AlterModelTable(
            name="playeranswer",
            table="quiz_sessions_playeranswer",
        ),
        migrations.AlterModelTable(
            name="playersession",
            table="quiz_sessions_playersession",
        ),
    ]
